# Generated by Django 4.2.16 on 2025-01-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("razvert", "0002_delete_choice"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("forecast", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
