# Generated by Django 4.2.16 on 2025-01-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("razvert", "0003_weatherrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="RandomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=10)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
